baseURL = "https://www.grahamhuck.dev/"
languageCode = "en-us"
title = "Graham Huck"
theme = "black-and-light"
author = "Graham Huck"
canonifyurls = true

pygmentsstyle       = "bw"
pygmentscodefences  = true


[params]
  sitename = "Graham Huck"
  disableWebFonts = false
  dateform = "2019-09-09 23:59:59"